import requests
import json
import time
import streamlit as st


def analyze_company(
    company_name, scraped_data, search_data, selected_model="openrouter/free"
):
    """
     Analyze company information using scraped and search data.

    Args:
        company_name (str): Name of the company.
        scraped_data (str): Data collected from web scraping.
        search_data (str): Data collected from search results.
        selected_model (str): AI model used for analysis.

    Returns:
        dict: Analysis results generated by the selected model.
    """

    api_key = st.secrets["OPENROUTER_API_KEY"]

    context = f"""
    Company: {company_name}
    Search Results: {search_data.get('description', '') if isinstance(search_data, dict) else search_data}
Website Content: {scraped_data}
    """

    prompt = f"""You are a professional business analyst. Analyze this company data and extract ONLY the most important information.

    Company: {company_name}
    Data: {context[:4000]}

    Return ONLY this JSON, nothing else, no extra text:
    {{
        "summary": "Write exactly 3 sentences about the company. What they do, their size/valuation, and their main market.",
        "products": ["Top 5-6 most important products/services only, keep each under 5 words"],
        "pain_points": ["exactly 4 most critical business challenges, each as one clear sentence"],
        "competitors": [
            {{"name": "Competitor Name Only", "website": "https://website.com"}}
        ]
    }}

    STRICT RULES:
    - Summary: exactly 3 sentences, clear and professional
    - Products: maximum 6 items, short names only
    - Pain Points: exactly 4 points, one sentence each
    - Competitors: exactly 4-5 competitors with real websites
    - NO extra explanation, NO markdown, ONLY valid JSON
    """

    # Selected model
    models = [selected_model]
    fallbacks = [
        "openrouter/free",
        "meta-llama/llama-3.3-70b:free",
        "google/gemma-3-4b-it:free",
        "poolside/laguna-xs-2.1:free",
    ]
    for m in fallbacks:
        if m not in models:
            models.append(m)

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    content = None

    for model in models:
        try:
            print(f"Trying: {model}")

            response = requests.post(
                url="https://openrouter.ai/api/v1/chat/completions",
                headers=headers,
                data=json.dumps(
                    {
                        "model": model,
                        "messages": [{"role": "user", "content": prompt}],
                        "reasoning": {"enabled": True},
                    }
                ),
            )

            result = response.json()

            if "choices" in result:
                print(f"Done : {model}")
                content = result["choices"][0]["message"]["content"]
                break
            else:
                print(f"Failed: {result.get('error', {}).get('message', '')}")
                time.sleep(5)

        except Exception as e:
            print(f"Error: {e}")
            time.sleep(5)

    if not content:
        return {
            "summary": "AI analysis failed",
            "products": [],
            "pain_points": [],
            "competitors": [],
        }

    try:
        content = content.strip()
        if "```json" in content:
            content = content.split("```json")[1].split("```")[0]
        elif "```" in content:
            content = content.split("```")[1].split("```")[0]
        return json.loads(content)
    except:
        return {
            "summary": content,
            "products": [],
            "pain_points": [],
            "competitors": [],
        }
